### ISSUE TITLE
Reinforced Spawner (Mob Spawner) x 1 is not a required item for this Quest! 

### ISSUE THREAD

**Issue by Hellcode48** [dmulloy2/Quests#1]
when I try to deliver a Spawner, it shows Reinforced Spawner (Mob Spawner) x 1 is not a required item for this Quest! how can i fix that?

here is the Quest:

``` yaml
custom19:
name: Ultra Breeding I
npc-giver-id: 241
ask-message: Hello!, I saw a New Breeding Method, Can you Craft me a Pig Spawner?
finish-message: Thanks!, heres some Cash
requirements:
quests:
- Farming I
- Farming II
- Farming III
- Farming IV
- Farming V
fail-requirement-message: You need to Complete Farming I-V First!
stages:
ordered:
'1':
items-to-deliver:
- name-MOB_SPAWNER:amount-1:displayname-§bReinforced Spawner:lore-§7Type%COLON% §bPig
npc-delivery-ids:
- 241
delivery-messages:
- You Delivered the Spawner!
rewards:
money: 500
```
